import { useEffect, useState } from 'react'
import { Check, Mail, RefreshCw, Trash2, UserPlus } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Message = { id:number; name:string; email:string; message:string; status:'new'|'read'|'replied'|'archived'; created_at:string; assigned_teacher_id:string|null; assigned_at:string|null }
type Teacher = { id:string; full_name:string|null; email:string }

export default function AdminMessages(){
  const [items,setItems]=useState<Message[]>([])
  const [teachers,setTeachers]=useState<Teacher[]>([])
  const [assignments,setAssignments]=useState<Record<number,string>>({})
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');const[m,t]=await Promise.all([supabase.from('contact_messages').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('id,full_name,email').eq('role','teacher').order('full_name')]);if(m.error)setError(m.error.message);else setItems((m.data||[]) as Message[]);if(t.error)setError(t.error.message);else setTeachers((t.data||[]) as Teacher[]);setLoading(false)}
  useEffect(()=>{void load();const channel=supabase.channel('admin-contact-messages').on('postgres_changes',{event:'*',schema:'public',table:'contact_messages'},()=>void load()).subscribe();return()=>{supabase.removeChannel(channel)}},[])
  const update=async(id:number,status:Message['status'])=>{const{error}=await supabase.from('contact_messages').update({status}).eq('id',id);if(error)setError(error.message);else setItems(x=>x.map(m=>m.id===id?{...m,status}:m))}
  const assign=async(id:number)=>{const teacherId=assignments[id]||null; if(!teacherId){setError('Select a teacher before assigning the message.');return} const{data:user}=await supabase.auth.getUser();const{error}=await supabase.from('contact_messages').update({assigned_teacher_id:teacherId,assigned_at:new Date().toISOString(),assigned_by:user.user?.id||null,status:'read'}).eq('id',id);if(error)setError(error.message);else{setItems(x=>x.map(m=>m.id===id?{...m,assigned_teacher_id:teacherId,assigned_at:new Date().toISOString(),status:m.status==='new'?'read':m.status}:m));setAssignments(x=>({...x,[id]:''}))}}
  const archive=async(id:number)=>update(id,'archived')
  const teacherName=(id:string|null)=>{const t=teachers.find(x=>x.id===id);return t?(t.full_name||t.email):'Assigned teacher'}
  return <section className="admin-panel"><div className="admin-panel-heading"><div><span className="admin-kicker">INBOX</span><h3>Contact messages</h3><p>Messages submitted from the public Contact page appear here in real time. Assign a message to a teacher to make it available in their workspace.</p></div><button className="admin-btn secondary" onClick={load}><RefreshCw size={14}/> Refresh</button></div>{error&&<div className="admin-error">{error}</div>}{loading?<div className="admin-empty">Loading messages…</div>:items.length===0?<div className="admin-empty"><Mail size={22}/><strong>No contact messages yet.</strong><span>New messages from the website will appear here.</span></div>:<div className="admin-message-list">{items.map(m=><article className={'admin-message '+(m.status==='new'?'unread':'')} key={m.id}><div className="admin-message-head"><div><strong>{m.name}</strong><a href={`mailto:${m.email}`}>{m.email}</a></div><time>{new Date(m.created_at).toLocaleString()}</time></div><p>{m.message}</p>{m.assigned_teacher_id?<div className="admin-assigned">Assigned to {teacherName(m.assigned_teacher_id)}</div>:<div className="admin-assignment"><select value={assignments[m.id]||''} onChange={e=>setAssignments(x=>({...x,[m.id]:e.target.value}))}><option value="">Select a teacher…</option>{teachers.map(t=><option value={t.id} key={t.id}>{t.full_name||t.email}</option>)}</select><button className="admin-btn secondary" onClick={()=>assign(m.id)} disabled={!assignments[m.id]}><UserPlus size={14}/> Assign teacher</button></div>}<div className="admin-message-actions"><span className={'admin-status '+m.status}>{m.status}</span>{m.status==='new'&&<button className="admin-btn secondary" onClick={()=>update(m.id,'read')}><Check size={14}/> Mark read</button>}{m.status!=='archived'&&<button className="admin-btn secondary" onClick={()=>archive(m.id)}><Trash2 size={14}/> Archive</button>}</div></article>)}</div>}</section>
}
