import {useEffect,useState} from 'react'
import {GraduationCap,Palette,LogOut,LayoutDashboard} from 'lucide-react'
import {supabase} from '../lib/supabase'
import AdminEditor from './AdminEditor'
import AdminTheme from './AdminTheme'

type Page='home'|'about'|'schedule'|'pricing'|'contact'
const labels:Record<Page,string>={home:'Home',about:'About',schedule:'Scheduling',pricing:'Pricing',contact:'Contact'}
export default function AdminSite(){
 const[s,setS]=useState<any>();const[a,setA]=useState(false);const[l,setL]=useState(true);const[p,setP]=useState<any>('overview');const[c,setC]=useState<any>({});const[t,setT]=useState<any>({});const[e,setE]=useState('');const[ok,setOk]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setS(data.session);if(data.session){const{data:x}=await supabase.from('admin_users').select('user_id').eq('user_id',data.session.user.id).maybeSingle();if(x){setA(true);load()}}setL(false)})},[])
 async function load(){const[x,y]=await Promise.all([supabase.from('site_content').select('page,content'),supabase.from('site_theme').select('*').eq('id',1).maybeSingle()]);if(x.error){setE(x.error.message);return}const n:any={};(x.data||[]).forEach((r:any)=>n[r.page]=r.content);setC(n);setT(y.data||{})}
 async function login(ev:any){ev.preventDefault();setE('');const f=new FormData(ev.currentTarget),r=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(r.error){setE(r.error.message);return}const{x}=await supabase.from('admin_users').select('user_id').eq('user_id',r.data.user.id).maybeSingle();if(!x){await supabase.auth.signOut();setE('This account is not authorized.');return}setS(r.data.session);setA(true);load()}
 async function save(){const q=p==='theme'?{...t,id:1}:{page:p,content:c[p]||{}};const r=await supabase.from(p==='theme'?'site_theme':'site_content').upsert(q,{onConflict:p==='theme'?'id':'page'});if(r.error)setE(r.error.message);else{setOk('Saved successfully.');setTimeout(()=>setOk(''),2500)}}
 if(l)return <div className="admin-loader">Loading...</div>
 if(!s||!a)return <Login error={e} submit={login}/>
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span><GraduationCap size={19}/></span><b>TeachWithJoy</b></div><Nav active={p==='overview'} onClick={()=>setP('overview')}><LayoutDashboard/> Overview</Nav>{(Object.keys(labels) as Page[]).map(x=><Nav key={x} active={p===x} onClick={()=>setP(x)}>{labels[x]}</Nav>)}<Nav active={p==='theme'} onClick={()=>setP('theme')}><Palette/> Color Theme</Nav><button className="admin-nav logout" onClick={()=>supabase.auth.signOut().then(()=>location.href='/')}><LogOut/> Sign out</button></aside><main className="admin-main"><header className="admin-topbar"><div><span className="admin-kicker">TEACHWITHJOY CMS</span><h2>{p==='overview'?'Overview':p==='theme'?'Color Theme':labels[p]}</h2></div><button className="admin-view-site" onClick={()=>location.href='/'}>View site</button></header>{e&&<div className="admin-error">{e}</div>}{ok&&<div className="admin-success">✓ {ok}</div>}{p==='overview'?<Overview go={setP}/>:p==='theme'?<AdminTheme theme={t} setTheme={setT} save={save}/>:<AdminEditor page={p} value={c[p]||{}} setContent={setC} save={save}/>}</main></div>
}
function Login({error,submit}:{error:string;submit:(e:any)=>void}){return <div className="admin-auth-page"><form className="admin-login-card" onSubmit={submit}><div className="admin-brand"><span><GraduationCap/></span><b>TeachWithJoy</b></div><div className="admin-kicker">ADMINISTRATION</div><h1>Manage your site.</h1><p>Sign in with an authorized administrator account.</p><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/>{error&&<div className="admin-error">{error}</div>}<button className="admin-btn primary">Sign in</button><button type="button" className="admin-back" onClick={()=>location.href='/'}>← Back to site</button></form></div>}
function Nav({children,active,onClick}:{children:React.ReactNode;active:boolean;onClick:()=>void}){return <button className={active?'admin-nav active':'admin-nav'} onClick={onClick}>{children}</button>}
function Overview({go}:{go:(p:any)=>void}){return <div className="admin-overview"><section className="admin-welcome"><div><span className="admin-kicker">CONTENT MANAGEMENT</span><h1>Keep TeachWithJoy up to date.</h1><p>Edit public pages and modify the color theme.</p></div><Palette size={28}/></section><div className="admin-card-grid">{(Object.keys(labels) as Page[]).map(x=><button className="admin-content-card" key={x} onClick={()=>go(x)}><span>{labels[x]}</span><strong>Edit content</strong></button>)}<button className="admin-content-card" onClick={()=>go('theme')}><span>Brand</span><strong>Modify color theme</strong></button></div></div>}
