import {useEffect,useRef,useState} from 'react'
import PublicSite from './PublicSite'
import {supabase} from '../lib/supabase'

export default function ManagedPublicSite(){
 const [data,setData]=useState<any>({});const [theme,setTheme]=useState<any>({});const root=useRef<HTMLDivElement>(null)
 useEffect(()=>{Promise.all([supabase.from('site_content').select('page,content'),supabase.from('site_theme').select('*').eq('id',1).maybeSingle()]).then(([c,t])=>{const n:any={};(c.data||[]).forEach((r:any)=>n[r.page]=r.content);setData(n);if(t.data)setTheme(t.data)})},[])
 useEffect(()=>{const r=document.documentElement;Object.entries(theme).forEach(([k,v])=>{if(k.endsWith('_color'))r.style.setProperty('--twj-'+k.replace('_color','').replace('_','-'),String(v))});const apply=()=>{const c=data;const q=(s:string)=>root.current?.querySelector(s) as HTMLElement|null;const set=(s:string,v:any)=>{const x=q(s);if(x&&v)x.textContent=String(v)};if(q('.hero')){set('.hero .eyebrow',c.home?.heroEyebrow);set('.hero-copy > p',c.home?.heroText);set('.hero h1',c.home?.heroTitle);const img=q('.hero-image img') as HTMLImageElement|null;if(img&&c.home?.heroImage)img.src=c.home.heroImage;set('.content-section .eyebrow',c.home?.whyEyebrow);set('.content-section h2',c.home?.whyTitle);set('.content-section p',c.home?.whyText);set('.testimonial-section strong',c.home?.testimonial);set('.testimonial-section span',c.home?.testimonialText);set('.testimonial-section small',c.home?.testimonialAuthor);set('.cta-section .eyebrow',c.home?.ctaEyebrow);set('.cta-section h2',c.home?.ctaTitle);set('.cta-section p',c.home?.ctaText)}else{set('.page-hero .eyebrow',c[location.hash.replace('#','')]?.eyebrow);set('.page-hero h1',c[location.hash.replace('#','')]?.title);set('.page-hero p',c[location.hash.replace('#','')]?.text)}if(q('.contact-detail')){const x=c.contact||{};const spans=root.current?.querySelectorAll('.contact-detail span');if(spans&&spans.length>2){spans[0].textContent=x.email||spans[0].textContent;spans[1].textContent=x.supportHours||spans[1].textContent;spans[2].textContent=x.onlineText||spans[2].textContent}}};apply();const o=new MutationObserver(()=>{o.disconnect();apply();o.observe(root.current!,{childList:true,subtree:true})});if(root.current)o.observe(root.current,{childList:true,subtree:true});return()=>o.disconnect()},[data,theme])
 return <div ref={root}><PublicSite/></div>
}
