import { useEffect, useMemo, useState } from 'react'
import { Activity, ChevronDown, GripVertical, LayoutDashboard, Menu, Plus, RefreshCw, Save, Shield, ToggleLeft, Workflow } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { getDashboardWidgets, getFeatureFlags, getNavigationItems, saveFeatureFlag, upsertDashboardWidget, upsertNavigation } from '../services/platform'
import type { DashboardWidgetDefinition, NavigationItem } from '../types/platform'

type Tab = 'roles' | 'navigation' | 'widgets' | 'features' | 'audit' | 'workflows' | 'settings'
const tabs: { id: Tab; label: string; icon: any }[] = [
  { id: 'roles', label: 'Roles & permissions', icon: Shield }, { id: 'navigation', label: 'Navigation', icon: Menu },
  { id: 'widgets', label: 'Dashboard widgets', icon: LayoutDashboard }, { id: 'features', label: 'Feature flags', icon: ToggleLeft },
  { id: 'audit', label: 'Audit log', icon: Activity }, { id: 'workflows', label: 'Workflows', icon: Workflow },
  { id: 'settings', label: 'Platform settings', icon: Save },
]

export default function PlatformAdmin() {
  const [tab, setTab] = useState<Tab>('roles')
  return <div className="platform-admin"><div className="platform-admin-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={16}/>{label}</button>)}</div>{tab === 'roles' && <RolesPanel/>}{tab === 'navigation' && <NavigationPanel/>}{tab === 'widgets' && <WidgetsPanel/>}{tab === 'features' && <FeaturesPanel/>}{tab === 'audit' && <AuditPanel/>}{tab === 'workflows' && <WorkflowPanel/>}{tab === 'settings' && <SettingsPanel/>}</div>
}

function NavigationPanel() {
  const [role, setRole] = useState('teacher'), [items, setItems] = useState<NavigationItem[]>([]), [loading, setLoading] = useState(false), [message, setMessage] = useState('')
  const load = async () => { setLoading(true); setItems(await getNavigationItems(role)); setLoading(false) }
  useEffect(() => { void load() }, [role])
  const update = (index: number, patch: Partial<NavigationItem>) => setItems(current => current.map((x, i) => i === index ? { ...x, ...patch } : x))
  const move = (from: number, to: number) => setItems(current => { const next = [...current]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next.map((x, i) => ({ ...x, sortOrder: i })) })
  const save = async () => { setMessage('Saving…'); const results = await Promise.all(items.map(item => upsertNavigation({ ...item, role_key: role, item_key: item.key }))); setMessage(results.every(r => !r.error) ? 'Navigation saved.' : 'Some navigation items could not be saved.'); await load() }
  return <section className="platform-panel"><PanelHead title="Navigation manager" text="Configure the menu per role without changing application code." refresh={load} loading={loading} action={<button className="platform-primary" onClick={save}><Save size={15}/> Save changes</button>}/><div className="platform-toolbar"><label>Role<select value={role} onChange={e => setRole(e.target.value)}><option>teacher</option><option>student</option><option>admin</option></select></label></div><div className="platform-list">{items.map((item, i) => <div className="platform-list-row" key={item.key}><GripVertical size={17}/><div className="platform-grow"><input value={item.label} onChange={e => update(i, { label: e.target.value })}/><small>{item.path} · {item.permission || 'no permission'}</small></div><button disabled={i === 0} onClick={() => move(i, i - 1)}>↑</button><button disabled={i === items.length - 1} onClick={() => move(i, i + 1)}>↓</button><input className="platform-check" type="checkbox" checked={item.enabled} onChange={e => update(i, { enabled: e.target.checked })}/></div>)}</div>{message && <div className="platform-message">{message}</div>}</section>
}

function WidgetsPanel() {
  const [role, setRole] = useState('teacher'), [widgets, setWidgets] = useState<DashboardWidgetDefinition[]>([]), [message, setMessage] = useState('')
  const load = async () => setWidgets(await getDashboardWidgets(role))
  useEffect(() => { void load() }, [role])
  const update = (i: number, patch: Partial<DashboardWidgetDefinition>) => setWidgets(current => current.map((x, n) => n === i ? { ...x, ...patch } : x))
  const save = async () => { setMessage('Saving…'); const results = await Promise.all(widgets.map(w => upsertDashboardWidget({ ...w, role_key: role, widget_key: w.key }))); setMessage(results.every(r => !r.error) ? 'Widgets saved.' : 'Some widgets could not be saved.'); await load() }
  return <section className="platform-panel"><PanelHead title="Dashboard widget manager" text="Control widget composition, order, visibility and feature gates." refresh={load} action={<button className="platform-primary" onClick={save}><Save size={15}/> Save changes</button>}/><div className="platform-toolbar"><label>Role<select value={role} onChange={e => setRole(e.target.value)}><option>teacher</option><option>student</option></select></label></div><div className="platform-list">{widgets.map((widget, i) => <div className="platform-list-row" key={widget.key}><GripVertical size={17}/><div className="platform-grow"><input value={widget.title} onChange={e => update(i, { title: e.target.value })}/><small>{widget.component} · {widget.permission || 'no permission'}</small></div><input type="number" min="0" value={widget.sortOrder} onChange={e => update(i, { sortOrder: Number(e.target.value) })}/><input className="platform-check" type="checkbox" checked={widget.enabled} onChange={e => update(i, { enabled: e.target.checked })}/></div>)}</div>{message && <div className="platform-message">{message}</div>}</section>
}

function FeaturesPanel() {
  const [flags, setFlags] = useState<Record<string, boolean>>({}), [message, setMessage] = useState('')
  const load = async () => { const next = await getFeatureFlags(); setFlags(next) }
  useEffect(() => { void load() }, [])
  const save = async (key: string, value: boolean) => { setFlags(x => ({ ...x, [key]: value })); const result = await saveFeatureFlag(key, value); setMessage(result.error ? `Unable to save ${key}.` : `${key} updated.`) }
  return <section className="platform-panel"><PanelHead title="Feature flags" text="Safely enable platform capabilities and stage future rollouts." refresh={load}/><div className="platform-flag-grid">{Object.entries(flags).map(([key, enabled]) => <div className="platform-flag" key={key}><div><strong>{key}</strong><small>Role-aware runtime flag</small></div><button className={enabled ? 'platform-toggle on' : 'platform-toggle'} onClick={() => void save(key, !enabled)}>{enabled ? 'Enabled' : 'Disabled'}</button></div>)}</div>{message && <div className="platform-message">{message}</div>}</section>
}

function RolesPanel() {
  const [roles, setRoles] = useState<any[]>([]), [permissions, setPermissions] = useState<any[]>([]), [selected, setSelected] = useState<string>('')
  const load = async () => { const [{ data: r }, { data: p }] = await Promise.all([supabase.from('platform_roles').select('*').order('label'), supabase.from('platform_permissions').select('*').order('module,permission_key')]); setRoles(r || []); setPermissions(p || []); if (!selected && r?.[0]) setSelected(r[0].id) }
  useEffect(() => { void load() }, [])
  const role = roles.find(r => r.id === selected), grouped = useMemo(() => permissions.reduce((a, p) => { (a[p.module || 'general'] ||= []).push(p); return a }, {} as Record<string, any[]>), [permissions])
  const toggle = async (permissionId: string, enabled: boolean) => { if (!role) return; if (enabled) await supabase.from('platform_role_permissions').upsert({ role_id: role.id, permission_id: permissionId }); else await supabase.from('platform_role_permissions').delete().eq('role_id', role.id).eq('permission_id', permissionId); await load() }
  const rolePermissionIds = new Set((awaitableRolePermissions(role?.id)) as string[])
  return <section className="platform-panel"><PanelHead title="Roles & permissions" text="Create extensible roles and assign least-privilege capabilities." refresh={load} action={<button className="platform-primary" onClick={async () => { const key = prompt('Role key (e.g. coordinator)'); if (!key) return; await supabase.from('platform_roles').insert({ role_key: key, label: key.replaceAll('_',' '), is_system: false }); await load() }}><Plus size={15}/> Add role</button>}/><div className="platform-role-layout"><div className="platform-role-list">{roles.map(r => <button className={selected === r.id ? 'active' : ''} key={r.id} onClick={() => setSelected(r.id)}><strong>{r.label}</strong><small>{r.role_key}</small></button>)}</div><div className="platform-permissions">{role ? Object.entries(grouped).map(([module, list]) => <div key={module}><h3>{module}</h3>{(list as any[]).map(p => <label className="permission-row" key={p.id}><input type="checkbox" checked={rolePermissionIds.has(p.id)} onChange={e => void toggle(p.id, e.target.checked)}/><span><strong>{p.label}</strong><small>{p.permission_key}</small></span></label>)}</div>) : <p>Select a role.</p>}</div></div></section>
}

async function awaitableRolePermissions(roleId?: string): Promise<string[]> { if (!roleId) return []; const { data } = await supabase.from('platform_role_permissions').select('permission_id').eq('role_id', roleId); return (data || []).map(x => x.permission_id) }

function AuditPanel() { const [rows, setRows] = useState<any[]>([]); const load = async () => { const { data } = await supabase.from('platform_activity_log').select('id,action,entity_type,entity_id,metadata,created_at,actor_id').order('created_at',{ascending:false}).limit(100); setRows(data || []) }; useEffect(() => { void load() }, []); return <section className="platform-panel"><PanelHead title="Audit log" text="Review configuration and platform activity with before/after metadata." refresh={load}/><div className="platform-audit">{rows.map(r => <div key={r.id}><div><strong>{r.action}</strong><small>{r.entity_type || 'platform'} · {r.actor_id || 'system'}</small></div><time>{new Date(r.created_at).toLocaleString()}</time><code>{JSON.stringify(r.metadata || {})}</code></div>)}</div></section> }
function WorkflowPanel() { const [rows,setRows]=useState<any[]>([]); const load=async()=>{const {data}=await supabase.from('platform_workflows').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{void load()},[]);return <section className="platform-panel"><PanelHead title="Workflow engine" text="Define trigger → condition → action automations. Execution can be enabled after the feature flag is turned on." refresh={load} action={<button className="platform-primary" onClick={async()=>{await supabase.from('platform_workflows').insert({name:'New workflow',trigger_type:'event',definition:{conditions:[],actions:[]}});await load()}}><Plus size={15}/> New workflow</button>}/><div className="platform-workflow-grid">{rows.map(r=><div className="platform-workflow-card" key={r.id}><strong>{r.name}</strong><small>{r.trigger_type}</small><button onClick={async()=>{await supabase.from('platform_workflows').update({enabled:!r.enabled}).eq('id',r.id);await load()}}>{r.enabled?'Enabled':'Disabled'}</button></div>)}</div></section>}
function SettingsPanel(){const [settings,setSettings]=useState(()=>{try{return JSON.parse(localStorage.getItem('teachwithjoy-platform-settings')||'{}')}catch{return {}}});const save=()=>{localStorage.setItem('teachwithjoy-platform-settings',JSON.stringify(settings));void supabase.from('platform_activity_log').insert({action:'platform.settings.updated',metadata:settings});alert('Platform settings saved.')};return <section className="platform-panel"><PanelHead title="Platform settings" text="Local defaults are retained immediately; organization-level persistence uses the platform schema."/><div className="platform-settings-form"><label>Platform name<input value={settings.name||'TeachWithJoy'} onChange={e=>setSettings({...settings,name:e.target.value})}/></label><label>Default timezone<input value={settings.timezone||'Asia/Manila'} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></label><label>Command palette<input type="checkbox" checked={settings.commandPalette!==false} onChange={e=>setSettings({...settings,commandPalette:e.target.checked})}/></label><button className="platform-primary" onClick={save}><Save size={15}/> Save settings</button></div></section>}
function PanelHead({title,text,refresh,loading,action}:{title:string;text:string;refresh?:()=>void;loading?:boolean;action?:React.ReactNode}){return <div className="platform-panel-head"><div><span className="platform-eyebrow">PLATFORM CONTROL</span><h2>{title}</h2><p>{text}</p></div><div className="platform-actions">{refresh&&<button onClick={refresh} disabled={loading}><RefreshCw size={15}/> Refresh</button>}{action}</div></div>}
