import { useState } from 'react'
import { GraduationCap, Users, CalendarDays, ShieldCheck, Sparkles, BookOpen, Clock3 } from 'lucide-react'
import { supabase } from '../lib/supabase'

const hero='https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=85'
export default function PublicSite(){const [mode,setMode]=useState('')
return <><header className="public-header"><Brand/><nav><a href="#home">Home</a><a href="#about">About</a><a href="#schedule">Schedule</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></nav><div className="header-actions"><button className="btn secondary" onClick={()=>setMode('login')}>Log In</button><button className="btn primary" onClick={()=>setMode('register')}>Sign Up</button></div></header>
<main><section className="hero" id="home"><div className="hero-copy"><span className="eyebrow">PERSONALIZED ONLINE LESSONS</span><h1>Learn Smarter,<br/><span>Achieve More</span></h1><p>Personalized online lessons to help you reach your goals. Flexible schedule, one-on-one guidance.</p><div className="hero-actions"><button className="btn primary xl" onClick={()=>setMode('register')}>Book a Session</button><a className="btn secondary xl" href="#about">View Schedule</a></div></div><div className="hero-image"><img src={hero} alt="Teacher and student online"/></div></section>
<section className="feature-strip"><Feature icon={<Users/>} title="1-on-1 Lessons" text="Personalized for you"/><Feature icon={<CalendarDays/>} title="Flexible Schedule" text="Book anytime"/><Feature icon={<ShieldCheck/>} title="Secure Payment" text="Safe and easy"/><Feature icon={<Sparkles/>} title="Proven Results" text="Students achieve more"/></section>
<section className="quote-card"><div className="quote-avatar">A</div><div><strong>“Joy is an amazing teacher!”</strong><span>Her lessons are easy to understand and very engaging. Highly recommended.</span><small>— Anna, Student</small></div></section>
<section className="content-section" id="about"><div><span className="eyebrow">WHY TEACHWITHJOY</span><h2>A calmer way to learn.</h2><p>Choose a subject, find a time that works, and book a session in a few clicks. Teachers manage subjects and availability from their dashboard.</p></div><div className="mini-cards"><Feature icon={<BookOpen/>} title="Dynamic Subjects" text="English, writing, business, and more"/><Feature icon={<Clock3/>} title="Live Availability" text="Only open teacher slots are bookable"/></div></section></main>
{mode&&<Auth mode={mode} close={()=>setMode('')} change={setMode}/>}</>}
function Feature({icon,title,text}:any){return <div className="feature"><div className="feature-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div></div>}
function Brand(){return <div className="brand"><div className="brand-icon"><GraduationCap size={20}/></div><strong>TeachWithJoy</strong></div>}
function Auth({mode,close,change}:any){const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('student'),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);setError('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name,role}}});setBusy(false);if(r.error)return setError(r.error.message);if(mode==='register'&&!r.data.session)return setError('Account created. Check your email to confirm it.');close()}return <div className="modal-backdrop"><div className="auth-modal"><button className="icon-btn close" onClick={close}>×</button><Brand/><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Log in to view your learning schedule.':'Choose your role and start learning or teaching.'}</p><form className="stack" onSubmit={submit}>{mode==='register'&&<><label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="student">Student</option><option value="teacher">Teacher</option></select></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy}>{busy?'Please wait...':mode==='login'?'Log In':'Create Account'}</button></form><div className="auth-switch">{mode==='login'?'New to TeachWithJoy?':'Already have an account?'} <button onClick={()=>change(mode==='login'?'register':'login')}>{mode==='login'?'Create one':'Log in'}</button></div></div></div>}
