create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  status text not null default 'new' check (status in ('new','read','replied','archived')),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "public_can_create_contact_messages" on public.contact_messages;
create policy "public_can_create_contact_messages" on public.contact_messages
for insert to anon, authenticated
with check (length(trim(name)) > 0 and length(trim(email)) > 3 and length(trim(message)) > 0);

drop policy if exists "admins_can_manage_contact_messages" on public.contact_messages;
create policy "admins_can_manage_contact_messages" on public.contact_messages
for all to authenticated using (public.is_admin()) with check (public.is_admin());

alter table public.site_theme add column if not exists site_name text default 'TeachWithJoy';
alter table public.site_theme add column if not exists footer_text text default 'Personalized learning, thoughtfully scheduled.';
alter table public.site_theme add column if not exists copyright_text text default '© 2026 TeachWithJoy. Learn with confidence.';

insert into public.site_theme (id, site_name, footer_text, copyright_text)
values (1, 'TeachWithJoy', 'Personalized learning, thoughtfully scheduled.', '© 2026 TeachWithJoy. Learn with confidence.')
on conflict (id) do update set
  site_name = coalesce(public.site_theme.site_name, excluded.site_name),
  footer_text = coalesce(public.site_theme.footer_text, excluded.footer_text),
  copyright_text = coalesce(public.site_theme.copyright_text, excluded.copyright_text);
