create table if not exists public.organizations (id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,status text not null default 'active' check(status in ('active','suspended','archived')),settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organization_members (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,status text not null default 'active',created_at timestamptz not null default now(),unique(organization_id,user_id));
create table if not exists public.platform_workflows (id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,name text not null,description text,enabled boolean not null default false,trigger_type text not null,definition jsonb not null default '{}'::jsonb,created_by uuid references auth.users(id),updated_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.platform_workflow_runs (id uuid primary key default gen_random_uuid(),workflow_id uuid not null references public.platform_workflows(id) on delete cascade,status text not null default 'queued' check(status in('queued','running','completed','failed','skipped')),trigger_payload jsonb not null default '{}'::jsonb,result jsonb not null default '{}'::jsonb,error text,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.platform_notification_templates (id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,template_key text not null,channel text not null check(channel in('in_app','email','push','sms')),subject text,body text not null,enabled boolean not null default true,variables jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,template_key,channel));
create table if not exists public.platform_notification_preferences (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,organization_id uuid references public.organizations(id) on delete cascade,channel text not null check(channel in('in_app','email','push','sms')),enabled boolean not null default true,updated_at timestamptz not null default now(),unique(user_id,organization_id,channel));
create table if not exists public.platform_configuration_versions (id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,config_type text not null,version integer not null,status text not null default 'draft' check(status in('draft','published','archived')),snapshot jsonb not null default '{}'::jsonb,created_by uuid references auth.users(id),created_at timestamptz not null default now(),published_at timestamptz,unique(organization_id,config_type,version));
create table if not exists public.platform_search_index (id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,entity_type text not null,entity_id uuid not null,title text not null,subtitle text,search_text text not null,metadata jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),unique(organization_id,entity_type,entity_id));
create index if not exists platform_search_text_idx on public.platform_search_index using gin(to_tsvector('simple',search_text));

a lter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.platform_workflows enable row level security;
alter table public.platform_workflow_runs enable row level security;
alter table public.platform_notification_templates enable row level security;
alter table public.platform_notification_preferences enable row level security;
alter table public.platform_configuration_versions enable row level security;
alter table public.platform_search_index enable row level security;

drop policy if exists platform_extensions_admin on public.organizations; create policy platform_extensions_admin on public.organizations for all to authenticated using (coalesce(public.is_admin(),false)) with check (coalesce(public.is_admin(),false));
drop policy if exists platform_org_members_admin on public.organization_members; create policy platform_org_members_admin on public.organization_members for all to authenticated using (coalesce(public.is_admin(),false) or user_id=auth.uid()) with check (coalesce(public.is_admin(),false) or user_id=auth.uid());
drop policy if exists platform_workflows_admin on public.platform_workflows; create policy platform_workflows_admin on public.platform_workflows for all to authenticated using (coalesce(public.is_admin(),false)) with check (coalesce(public.is_admin(),false));
drop policy if exists platform_workflow_runs_admin on public.platform_workflow_runs; create policy platform_workflow_runs_admin on public.platform_workflow_runs for select to authenticated using (coalesce(public.is_admin(),false));
drop policy if exists platform_notification_templates_admin on public.platform_notification_templates; create policy platform_notification_templates_admin on public.platform_notification_templates for all to authenticated using (coalesce(public.is_admin(),false)) with check (coalesce(public.is_admin(),false));
drop policy if exists platform_notification_preferences_self on public.platform_notification_preferences; create policy platform_notification_preferences_self on public.platform_notification_preferences for all to authenticated using (user_id=auth.uid() or coalesce(public.is_admin(),false)) with check (user_id=auth.uid() or coalesce(public.is_admin(),false));
drop policy if exists platform_configuration_versions_admin on public.platform_configuration_versions; create policy platform_configuration_versions_admin on public.platform_configuration_versions for all to authenticated using (coalesce(public.is_admin(),false)) with check (coalesce(public.is_admin(),false));
drop policy if exists platform_search_index_read on public.platform_search_index; create policy platform_search_index_read on public.platform_search_index for select to authenticated using (true);
drop policy if exists platform_search_index_admin on public.platform_search_index; create policy platform_search_index_admin on public.platform_search_index for all to authenticated using (coalesce(public.is_admin(),false)) with check (coalesce(public.is_admin(),false));
